drop table EMPLOYEE;

CREATE TABLE EMPLOYEE (
    ID int(10) NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    AGE SMALLINT(2),
    SALARY double(6 , 2 ),
    PRIMARY KEY (ID)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8


DELETE * FROM EMPLOYEE

INSERT INTO EMPLOYEE
VALUES (1,'Abdul Raquib',40,5000.00);
INSERT INTO employee
VALUES (3,'Abdul Raafay',10,1000.00);